openimis/openimis-be-api_fhir_r4_py

- api_fhir_r4/converters/claimResponseConverter.py
- api_fhir_r4/serializers/__init__.py
- api_fhir_r4/serializers/claimResponseSerializer.py
- api_fhir_r4/tests/mixin/claimResponseTestMixin.py
- api_fhir_r4/tests/test/test_claimResponse.json
- api_fhir_r4/tests/test_claimResponseConverter.py
- api_fhir_r4/views.py
Ticket: [OAI-16](https://openimis.atlassian.net/browse/OAI-16)
> OAI-16: Added PUT method to claimResponse endpoint

- api_fhir_r4/apps.py
- api_fhir_r4/configurations/R4ClaimConfig.py
- api_fhir_r4/configurations/__init__.py
- api_fhir_r4/converters/claimConverter.py
- api_fhir_r4/models/claim.py
- api_fhir_r4/serializers/claimSerializer.py
TICKET: [OP-285](https://openimis.atlassian.net/browse/OP-285)
> OP-285: Added attachment handling to claim endpoint

- api_fhir_r4/converters/claimConverter.py
TICKET: [OP-285](https://openimis.atlassian.net/browse/OP-285)
> OP-285: Fixed handling attachments from files

- api_fhir_r4/converters/__init__.py
- api_fhir_r4/converters/containedResourceConverter.py
- api_fhir_r4/mixins.py
- api_fhir_r4/serializers/claimSerializer.py
- api_fhir_r4/tests/test_containedResourceConverter.py
- api_fhir_r4/tests/test_mixins.py
- api_fhir_r4/views.py
TICKET: [OAI-27](https://openimis.atlassian.net/browse/OAI-27)
> OAI-27: Added contained resources for  FHIR Claim 

- api_fhir_r4/mixins.py
- api_fhir_r4/serializers/claimSerializer.py
TICKET: [OP-297](https://openimis.atlassian.net/browse/OP-297)
> OP-297: Fix contained resource ids and references

- api_fhir_r4/converters/patientConverter.py
Adds extension with family reference to FHIR Patient, required by Claim AI.
> OAI-38: Added group extension to patient 

- api_fhir_r4/converters/claimConverter.py
- api_fhir_r4/converters/medicationConverter.py
- api_fhir_r4/views.py
TICKET: [OP-319](https://openimis.atlassian.net/browse/OP-319)
Most of the changes introduced in  master commits were already included in https://github.com/openimis/openimis-be-api_fhir_r4_py/pull/2 
* Configuration: 
Configuration conflicts were caused by replacing `cls.get_config` with `cls.get_config_attribute` Change required by docker instance.
* generalConfiguration.py
* R4CoverageConfig.py
* R4LocationConfig.py
* Converters
* claumConverter.py - `FHIRRequestProcessException` is raised if claim without admin is converted
* claimResponseConverter.py - `build_fhir_item_adjudication` refactorized
* locationConverter.py - code style
* \_\_init\_\_ - code style
* apps.py - default config moved from apps.py to defaultConfig.py
* views.py - `PractitionerRoleViewSet.list` don't require …
> OP-319: Resolve conflicts with master branch

- api_fhir_r4/configurations/R4IdentifierConfig.py
- api_fhir_r4/configurations/__init__.py
- api_fhir_r4/converters/__init__.py
- api_fhir_r4/converters/activityDefinitionConverter.py
- api_fhir_r4/converters/claimConverter.py
- api_fhir_r4/converters/claimResponseConverter.py
- api_fhir_r4/converters/communicationRequestConverter.py
- api_fhir_r4/converters/conditionConverter.py
- api_fhir_r4/converters/containedResourceConverter.py
- api_fhir_r4/converters/contractConverter.py
- api_fhir_r4/converters/coverageConventer.py
- api_fhir_r4/converters/coverageConverter.py
- api_fhir_r4/converters/healthcareServiceConverter.py
- api_fhir_r4/converters/locationConverter.py
- api_fhir_r4/converters/locationSiteConverter.py
- api_fhir_r4/converters/medicationConverter.py
- api_fhir_r4/converters/patientConverter.py
- api_fhir_r4/converters/policyCoverageEligibilityRequestConverter.py
- api_fhir_r4/converters/practitionerConverter.py
- api_fhir_r4/converters/practitionerRoleConverter.py
- api_fhir_r4/converters/referenceConverterMixin.py
- api_fhir_r4/mixins.py
- api_fhir_r4/serializers/__init__.py
- api_fhir_r4/serializers/claimSerializer.py
[OAI-52](https://openimis.atlassian.net/browse/OAI-52)
Database ID is added to FHIR identifiers. The possibility to select which identifier is to be used as resource primary id and reference was also added. 
Additional changes: 
- Fixed bug with random uuids in claim item field entries
> OAI-52: Database ID Identifiers added

- api_fhir_r4/serializers/__init__.py
- api_fhir_r4/urls.py
- api_fhir_r4/views.py
TICKET: https://openimis.atlassian.net/browse/OE0-2
1st part of ticket: "Add /api_fhir_r4/login endpoint that will generate the JWT and sent it back to the client. Same payload required by GQL (username, password) must be required." 
Include fix https://github.com/openimis/openimis-be-api_fhir_r4_py/commit/3cfd17705770b32862c24ae3d7315b12299a1644
> OE0-2: 1. Add /api_fhir_r4/login endpoint that will generate the JWT

- api_fhir_r4/permissions.py
- api_fhir_r4/views.py
TICKET: https://openimis.atlassian.net/browse/OE0-4
Part regarding adding new perms for Group, Organization. Added lacking perms values for existing permissions.
> OE0-4: added new perms + fixed queryset for GroupViewSet

- api_fhir_r4/permissions.py
TICKET: https://openimis.atlassian.net/browse/OE0-4
added rest of perms after adding lacking ones in another modules.
> OE0-4: updating perms in fhir r4 module

- api_fhir_r4/views.py
TICKET: https://openimis.atlassian.net/browse/OE0-2
changing import statement after migrating jwt auth services into core module:
related PRs:
1. https://github.com/openimis/openimis-be_py/pull/40
2. https://github.com/openimis/openimis-be-core_py/pull/65
> OE0-2: changes after migration jwt to core module

- api_fhir_r4/tests/test/test_login.json
- api_fhir_r4/tests/test/test_login_bad_credentials.json
- api_fhir_r4/tests/test/test_login_bad_payload.json
- api_fhir_r4/tests/test_api_login.py
TICKET:  https://openimis.atlassian.net/browse/OE0-9
1st part: test related to 'login' endpoint
scenarios:
- good user (created or getting during test if exists) - should return 200
- bad credentials - should return 401
- bad payload - should return 400
> OE0-9: added unit tests for 'login' endpoint

- api_fhir_r4/converters/__init__.py
- api_fhir_r4/converters/patientConverter.py
TICKET: https://openimis.atlassian.net/browse/OE0-21
Changed mapping of Patient address according to the 'Patient' Profile.
Including minor fixes in code of PatientConverter.
> OE0-21: Patient: address not correctly mapped 

- api_fhir_r4/configurations/__init__.py
- api_fhir_r4/converters/__init__.py
- api_fhir_r4/converters/activityDefinitionConverter.py
- api_fhir_r4/converters/claimConverter.py
- api_fhir_r4/converters/containedResourceConverter.py
- api_fhir_r4/converters/patientConverter.py
- api_fhir_r4/converters/personConverterMixin.py
- api_fhir_r4/converters/referenceConverterMixin.py
- api_fhir_r4/models/__init__.py
- api_fhir_r4/models/imisModelEnums.py
Developed as part of  [E0-20](https://openimis.atlassian.net/browse/OE0-20). 
Changes in this PR also include minor code refactor.
> E0-20: Ensure Claim AI compability

- api_fhir_r4/configurations/generalConfiguration.py
- api_fhir_r4/converters/patientConverter.py
- api_fhir_r4/defaultConfig.py
- api_fhir_r4/mapping/__init__.py
- api_fhir_r4/mapping/patientMapping.py
TICKET: https://openimis.atlassian.net/browse/OE0-26
PR includes changes from feature/OE0-21 from that PR regarding address. https://openimis.atlassian.net/browse/OE0-21
> OE0-26: Patient: Replace link with contact for insuree relationship

- api_fhir_r4/converters/patientConverter.py
- api_fhir_r4/mapping/patientMapping.py
TICKET: https://openimis.atlassian.net/browse/OE0-32
- Adding new extensions
- updating contact with adding displat/code and fixing URL. 
- Removing extensions not used like ValidityFrom, Poverty etc
- uppdate crating build_imis_extension and build_imis_address
related PR - https://github.com/openimis/openimis-be-api_fhir_r4_py/pull/31
> OE0-32: added new extensions, update existing and remove not used in profile

- api_fhir_r4/converters/patientConverter.py
- api_fhir_r4/mapping/patientMapping.py
TICKET: https://openimis.atlassian.net/browse/OE0-24
includes PR https://github.com/openimis/openimis-be-api_fhir_r4_py/pull/30 from TICKET https://openimis.atlassian.net/browse/OE0-32
ORDER of merging into develop after approving PRs:
1. OE0-32
2. OE0-24
> OE0-24: maritalStatus comply

- api_fhir_r4/converters/__init__.py
- api_fhir_r4/converters/operationOutcomeConverter.py
- api_fhir_r4/converters/patientConverter.py
- api_fhir_r4/serializers/patientSerializer.py
TICKET: https://openimis.atlassian.net/browse/OE0-47
changes:
- update some IMIS object build methods to satisfy openIMIS Patient profile
related PR: https://github.com/openimis/openimis-be-api_fhir_r4_py/pull/32. this PR contains  PR 32.
> OE0-47: Satisfy POST and PUT in Patient profile

- api_fhir_r4/converters/patientConverter.py
- api_fhir_r4/serializers/patientSerializer.py
TICKET: https://openimis.atlassian.net/browse/OE0-35
PatientSerializer changes:
- added creating insuree from service in insuree module
- added created photo file from service in insuree module
contains one commit related to feature/OE0-28 - https://openimis.atlassian.net/browse/OE0-28 - "GET" slice for photo.
> OE0-35: used insuree service and photo comply with Profile

- api_fhir_r4/mixins.py
TICKET: https://openimis.atlassian.net/browse/OE0-49
> OE0-49: fixed contained resources - field 'id'

- api_fhir_r4/configurations/R4IdentifierConfig.py
- api_fhir_r4/configurations/R4LocationConfig.py
- api_fhir_r4/configurations/__init__.py
- api_fhir_r4/converters/__init__.py
- api_fhir_r4/converters/locationConverter.py
- api_fhir_r4/converters/operationOutcomeConverter.py
- api_fhir_r4/defaultConfig.py
- api_fhir_r4/mapping/__init__.py
- api_fhir_r4/mapping/locationMapping.py
- api_fhir_r4/mixins.py
- api_fhir_r4/serializers/locationSerializer.py
- api_fhir_r4/views/fhir/location.py
TICKET: [E0-40](https://openimis.atlassian.net/browse/OE0-40)
> E0-40: Satisfy OpenIMISLocation profile

- api_fhir_r4/converters/patientConverter.py
- api_fhir_r4/tests/test/test_group.json
- api_fhir_r4/tests/test/test_patient.json
- api_fhir_r4/tests/test_api_patient.py
TICKET: https://openimis.atlassian.net/browse/OE0-30
changes:
- added validation for required fields in 'Patient' according to: https://openimis.github.io/openimis_fhir_r4_ig/StructureDefinition-openimis-patient.html
- added tests for checking if validation works
> OE0-30: Validator for Patient FHIR object

- api_fhir_r4/configurations/R4ClaimConfig.py
- api_fhir_r4/converters/__init__.py
- api_fhir_r4/converters/activityDefinitionConverter.py
- api_fhir_r4/converters/claimConverter.py
- api_fhir_r4/defaultConfig.py
- api_fhir_r4/mapping/claimMapping.py
Changes:
- Updated `ClaimConverter` to fit current Claim resource
- Added missing mappings and config fields
- Moved some generic structure building to base converter for reuse
[https://openimis.atlassian.net/browse/OE0-66](https://openimis.atlassian.net/browse/OE0-66)
> OE0-66: Satisfy OpenIMISClaim profile

- api_fhir_r4/converters/activityDefinitionConverter.py
- api_fhir_r4/converters/groupConverter.py
- api_fhir_r4/converters/insurancePlanConverter.py
- api_fhir_r4/converters/medicationConverter.py
- api_fhir_r4/converters/patientConverter.py
- api_fhir_r4/tests/mixin/activityDefinitionTestMixin.py
- api_fhir_r4/tests/mixin/groupTestMixin.py
- api_fhir_r4/tests/mixin/insurancePlanTestMixin.py
- api_fhir_r4/tests/mixin/medicationTestMixin.py
- api_fhir_r4/tests/mixin/patientTestMixin.py
- api_fhir_r4/tests/test/test_activity_definition.json
- api_fhir_r4/tests/test/test_claimResponse.json
- api_fhir_r4/tests/test/test_group.json
- api_fhir_r4/tests/test/test_insurance_plan.json
- api_fhir_r4/tests/test/test_medication.json
- api_fhir_r4/tests/test/test_patient.json
- api_fhir_r4/tests/test_api_group.py
- api_fhir_r4/tests/test_api_medication.py
- api_fhir_r4/tests/test_api_patient.py
TICKET: https://openimis.atlassian.net/browse/OE0-70
fixing code in identifier when the 'code' is used. 
+ including improving/fixes for Patient/Group
this PR should be merged after merging https://github.com/openimis/openimis-be-api_fhir_r4_py/pull/54
> OE0-70: Wrong code for Code Identifiers + fixes for Patient/Group

- api_fhir_r4/converters/healthFacilityOrganisationConverter.py
- api_fhir_r4/mapping/hfOrganizationMapping.py
- api_fhir_r4/mapping/locationMapping.py
TICKET: https://openimis.atlassian.net/browse/OE0-71
I deleted hardcoded base url to openIMIS profiles. 
This ticket should be merged after merging https://github.com/openimis/openimis-be-api_fhir_r4_py/pull/54  and https://github.com/openimis/openimis-be-api_fhir_r4_py/pull/56
Order of merge:
1.https://github.com/openimis/openimis-be-api_fhir_r4_py/pull/54
2.https://github.com/openimis/openimis-be-api_fhir_r4_py/pull/56
> OE0-71: removed hardcoded url to openIMIS profiles

- api_fhir_r4/converters/claimConverter.py
- api_fhir_r4/converters/operationOutcomeConverter.py
- api_fhir_r4/serializers/claimSerializer.py
Change required for CI Check in [Claim Module PR ](https://github.com/openimis/openimis-be-claim_py/runs/4881569685?check_suite_focus=true).
> OAI-62: Fixed imports from claim module

- .github/workflows/openmis-module-test.yml
- api_fhir_r4/converters/insurancePlanConverter.py
- api_fhir_r4/tests/mixin/insurancePlanTestMixin.py
Rebased version of https://github.com/openimis/openimis-be-api_fhir_r4_py/pull/73
> bulk-update-openmis-module-test.yml V2

- api_fhir_r4/mapping/invoiceMapping.py
- api_fhir_r4/signals.py
- api_fhir_r4/subscriptions/notificationClient.py
- api_fhir_r4/subscriptions/subscriptionCriteriaFilter.py
- api_fhir_r4/subscriptions/subscriptionSerializer.py
[https://openimis.atlassian.net/browse/OPL-68](https://openimis.atlassian.net/browse/OPL-68)
Changes:
- Added `SubscriptionCriteriaFilter` used to generate list of matching subscriptions for a given model
- Added appropriate signal bindings for creation of `Insuree`, `Invoice` and `Bill` resources
- Fixed missing bill mappings for `unconditional_cash_payment` calculation rule (NEEDS PROPER FHIR IG ENTRY)
> OPL-68 Add signal bindings for Subscription handling

- api_fhir_r4/signals.py
- api_fhir_r4/subscriptions/subscriptionSerializer.py
- api_fhir_r4/urls.py
[https://openimis.atlassian.net/browse/OPL-90](https://openimis.atlassian.net/browse/OPL-90
Changes:
- Added Organisation to list of subscribable resources
- Added signal binding for HealthFacility
- Moved signal binding code after module check (preventing importing of non-existing models)
> OPL-90: Extend the notifications to allow subscribing Health Facilities

- api_fhir_r4/serializers/contractSerializer.py
part of TICKET: https://openimis.atlassian.net/browse/OPL-91
related PR: https://github.com/openimis/openimis-be-policy_py/pull/24
> OPL-91: changed service for Policy in Contract Serializer

- api_fhir_r4/converters/patientConverter.py
- api_fhir_r4/mixins.py
- api_fhir_r4/serializers/__init__.py
- api_fhir_r4/serializers/patientSerializer.py
- api_fhir_r4/views/fhir/practitioner.py
- api_fhir_r4/views/fhir/practitioner_role.py
TICKET: [OE0-106](https://openimis.atlassian.net/browse/OE0-106)
Additional changes: 
* Log stack trace of failed mapping in Serializer in DEBUG mode. 
* Fixed multiserialzier for multiidentifier 
* Fixed family location resource
> OE0-106: Fixed practitioner viewset 

- api_fhir_r4/converters/claimConverter.py
- api_fhir_r4/multiserializer/mixins.py
- api_fhir_r4/views/fhir/practitioner.py
TICKET: [OE0-104](https://openimis.atlassian.net/browse/OE0-104)
> OE0-104: Improve performance of Claims and Multiserialized resources

- api_fhir_r4/converters/groupConverter.py
- api_fhir_r4/converters/referenceConverterMixin.py
- api_fhir_r4/tests/mixin/groupTestMixin.py
- api_fhir_r4/tests/test/test_claim_contained.json
- api_fhir_r4/tests/test/test_group.json
- api_fhir_r4/tests/test_api_claim_contained.py
- api_fhir_r4/tests/test_api_group.py
Ticket: [OE0-108](https://openimis.atlassian.net/browse/OE0-108)
> OE0-108: Change Group members FHIR -> IMIS mapping

- api_fhir_r4/converters/contractConverter.py
- api_fhir_r4/converters/groupConverter.py
- api_fhir_r4/converters/patientConverter.py
- api_fhir_r4/converters/referenceConverterMixin.py
- api_fhir_r4/tests/mixin/patientTestMixin.py
- api_fhir_r4/tests/test/test_patient.json
- api_fhir_r4/tests/test_api_contract.py
TICKET: [OP-778](https://openimis.atlassian.net/browse/OP-778)
Additional changes: 
- Patient resource is enforced to use only one address.
> OP-778: Contract can be created using Patient subject

- api_fhir_r4/apps.py
- api_fhir_r4/converters/coverageEligibilityRequestConverter.py
Eligibility was checked against insuree claim instead of product. 
TICKET: [OP-809](https://openimis.atlassian.net/browse/OP-809)
> OP-809: Fixed item/service in eligiblity request

- api_fhir_r4/mapping/patientMapping.py
Handle the gender mapping if 'other' is not used in db
https://openimis.atlassian.net/browse/OP-843
> OP-843: Gender mapping throws an error if gender 'other' does not exist in the database 

- api_fhir_r4/views/fhir/organisation.py
Ticket: [OTC-685](https://openimis.atlassian.net/browse/OTC-685)
> OTC-685: Fixed organization code filtering

- api_fhir_r4/migrations/0001_initial.py
- api_fhir_r4/models/subscription.py
> Django 3.1

- api_fhir_r4/tests/mixin/claimAdminPractitionerRoleTestMixin.py
- api_fhir_r4/tests/mixin/claimResponseTestMixin.py
- api_fhir_r4/tests/mixin/claimTestMixin.py
- api_fhir_r4/tests/mixin/communicationRequestTestMixin.py
- api_fhir_r4/tests/mixin/communicationTestMixin.py
- api_fhir_r4/tests/mixin/coverageEligibilityRequestTestMixin.py
- api_fhir_r4/tests/mixin/enrolmentOfficerPractitionerRoleTestMixin.py
- api_fhir_r4/tests/mixin/patientTestMixin.py
- api_fhir_r4/tests/testCodeSystem/test_api_codeDiagnosis.py
- api_fhir_r4/tests/testCodeSystem/test_api_codeGroupConfirmationType.py
- api_fhir_r4/tests/testCodeSystem/test_api_codeGroupType.py
- api_fhir_r4/tests/testCodeSystem/test_api_codeHFOrganizationLegalForm.py
- api_fhir_r4/tests/testCodeSystem/test_api_codeHFOrganizationLevel.py
- api_fhir_r4/tests/testCodeSystem/test_api_codePHOrganisationActivity.py
- api_fhir_r4/tests/testCodeSystem/test_api_codePHOrganisationLegalForm.py
- api_fhir_r4/tests/testCodeSystem/test_api_codePatientContactRelationship.py
- api_fhir_r4/tests/testCodeSystem/test_api_codePatientEducationLevel.py
- api_fhir_r4/tests/testCodeSystem/test_api_codePatientIdentificationType.py
- api_fhir_r4/tests/testCodeSystem/test_api_codePatientProfession.py
- api_fhir_r4/tests/test_api_patient.py
- api_fhir_r4/tests/test_subscriptionService.py
- api_fhir_r4/tests/test_timeUtils.py
[https://openimis.atlassian.net/browse/OP-868](https://openimis.atlassian.net/browse/OP-868)
Changes:
- Changed handling of JSON fields from JSON strings to python dictionaties (Django 3.2 update)
- Fixed TestCase handling (added all missing calls to super.setUpClass, super.setUp, removed unecessary teardowns)
- Removed some unused code/comments/imports
- Fixed code formatting
> OP-868 Fix CI issues caused by Django 3.2 update

- setup.py
update library so the tests would work
> update pydantic package

- .github/workflows/openmis-module-test-psql.yml
- api_fhir_r4/paymentNotice/converter/to_imis_converter.py
- api_fhir_r4/serializers/codeSystemSerializer.py
- api_fhir_r4/tests/mixin/billInvoiceTestMixin.py
- api_fhir_r4/tests/mixin/invoiceTestMixin.py
- api_fhir_r4/tests/subscriptions/manager.py
[https://openimis.atlassian.net/browse/CM-188](https://openimis.atlassian.net/browse/CM-188)
> CM-188 Adjust backend part to handle payments for Social Protection

- api_fhir_r4/signals.py
[https://openimis.atlassian.net/browse/CM-234](https://openimis.atlassian.net/browse/CM-234)
> CM-234 Fixed error handling in signals

- api_fhir_r4/paymentNotice/mapping/status_mapping.py
- api_fhir_r4/tests/mixin/paymentNoticeTestMixin.py
TICKET: https://openimis.atlassian.net/browse/CM-315
> CM-315: replace PAYED to PAID

- setup.py
Ticket: https://openimis.atlassian.net/browse/OP-1676
Changes:
- Added version of pydantic.
> OP-1676: Pydantic version specified.

- api_fhir_r4/serializers/contractSerializer.py
relates to https://github.com/openimis/openimis-be-contribution_py/pull/59
> update contribution service

- api_fhir_r4/containedResources/converters.py
- api_fhir_r4/converters/operationOutcomeConverter.py
- api_fhir_r4/converters/policyHolderOrganisationConverter.py
- api_fhir_r4/multiserializer/mixins.py
- api_fhir_r4/permissions.py
- api_fhir_r4/tests/test_api_patient.py
- api_fhir_r4/views/fhir/location.py
MERGING develop into release/24.04
> MERGING develop into release/24.04
