openimis/openimis-be-api_fhir_r4_py

api_fhir_r4/converters/activityDefinitionConverter.py, api_fhir_r4/converters/medicationConverter.py
Change required by AI module which use ServLevel as one of evaluation parameters. New entry is added to current use context for both Medication and ActivityDefinition. 
New values have format: 
* For Activity Definition
```json
{
"code": {
"code": "useContextLevel"
},
"valueCodeableConcept": {
"coding": [
{
"code": "S",  //ServLevel value 
"display": "Simple Service"  // Simple Service, Visit, Day of stay, Hospital case
}
],
"text": "Service Level"
}
}
```
* For Medication
```json
{
"url": "useContextLevel",
"valueUsageContext": {
"code": {
"code": "level"
},
"valueCodeableConcept": {
"coding": [
{
"code": "M", // Fixed value
"display": "Medication"
}
],
"text": "Item Level"
}
}
}
```
=> OAI-38: Added level to useContext

api_fhir_r4/tests/test_api_authorization.py, api_fhir_r4/tests/test_api_login.py
TICKET: https://openimis.atlassian.net/browse/OE0-9
+remove redundant line from last PR https://github.com/openimis/openimis-be-api_fhir_r4_py/pull/22
2nd part: tests related to processing token in auth header:
scenarios:
- 200 HTTP Code if token is valid  
- 401 HTTP Code if Authorization header is missing  
- 401 HTTP Code if Bearer prefix is missing 
- 401 HTTP Code if error on decoding Authorization header   
- 401 HTTP Code if structure of token is not proper (too many extra words etc)
- 403 HTTP Code - Forbidden - when trying to access to resource which user doesn't have any permissions to do operations.
=> OE0-9: added unit tests for auth header processing

api_fhir_r4/urls.py, api_fhir_r4/views.py, setup.py
TICKET: https://openimis.atlassian.net/browse/OE0-11
According to:
"if it is not part of openimis.json in assembly then it is not used but if not used it should not be displayed in the REST API available endpoints"
I imported 'openimis_apps()' so as to have the list of imis modules. Then I checked if module is included in list. If yes - then I can register endpoint related to this module.
=> OE0-11: Add routes if modules are used

api_fhir_r4/converters/insurancePlanConverter.py, api_fhir_r4/tests/mixin/insurancePlanTestMixin.py, api_fhir_r4/tests/test/test_insurance_plan.json
NOTE: after merging https://github.com/openimis/openimis-be-api_fhir_r4_py/pull/42 I will rebase this PR to develop. 
TICKET: https://openimis.atlassian.net/browse/OE0-51
improving processing extensions ('period' and 'discount')
=> OE0-51: InsurancePlan - period and discount extension mapping

api_fhir_r4/converters/__init__.py, api_fhir_r4/converters/healthFacilityOrganisationConverter.py, api_fhir_r4/converters/operationOutcomeConverter.py, api_fhir_r4/converters/patientConverter.py, api_fhir_r4/converters/personConverterMixin.py, api_fhir_r4/converters/policyHolderOrganisationConverter.py, api_fhir_r4/mapping/hfOrganizationMapping.py, api_fhir_r4/mixins.py, api_fhir_r4/models/imisModelEnums.py, api_fhir_r4/multiserializer/__init__.py, api_fhir_r4/multiserializer/mixins.py, api_fhir_r4/multiserializer/modelViewset.py, api_fhir_r4/multiserializer/serializerClass.py, api_fhir_r4/paginations.py, api_fhir_r4/serializers/__init__.py, api_fhir_r4/serializers/healthFacilityOrganisationSerializer.py, api_fhir_r4/serializers/policyHolderOrganisationSerializer.py, api_fhir_r4/views/fhir/fhir_base_viewset.py, api_fhir_r4/views/fhir/organisation.py
TICKET: [OE0-25](https://openimis.atlassian.net/browse/OE0-25)
Additional changes: 
1. Added Multiserializer Mixins for viewsets. 
Allows to use multiple serializer by one endpoint, and therefore make it easier to map multiple IMIS resources to single FHIR endpoint in future. Default multi-serializer mixins for create/update assume that only one of the listed serializers will be valid to process the given request. This protects against duplicate actions by more than one serializers. Retrieving an item by its identifier works similary. If serialirers are pointing to more than one object exception will be thrown. 
2. OperationOutcome handles ValidationError
=> OE0-25: Added multi-serailizer logic for HF Organisation

api_fhir_r4/converters/activityDefinitionConverter.py, api_fhir_r4/tests/mixin/activityDefinitionTestMixin.py, api_fhir_r4/tests/test_activityDefinitionConverter.py, api_fhir_r4/tests/test_timeUtils.py
Changes:
- `ActivityDefinition` age, gender and workflow contexts are now optional
- Fixed `TimeUtils` tests
[https://openimis.atlassian.net/browse/OE0-67](https://openimis.atlassian.net/browse/OE0-67)
=> OE0-67: ActivityDefinition workflow use context should be optional

api_fhir_r4/converters/patientConverter.py, api_fhir_r4/tests/mixin/patientTestMixin.py, api_fhir_r4/tests/test/test_patient.json, api_fhir_r4/tests/test_api_patient.py
Developed as part of [OAI-61](https://openimis.atlassian.net/jira/software/c/projects/OAI/boards/28?modal=detail&selectedIssue=OAI-61). Local instance of api_fhir_r4 module failed to create contained resource for claim due to invalid photo url.
=> OAI-61: Insuree photo url use localhost if site root is empty

api_fhir_r4/tests/mixin/__init__.py, api_fhir_r4/tests/mixin/invoiceTestMixin.py, api_fhir_r4/tests/mixin/logInMixin.py, api_fhir_r4/tests/test_api_authorization.py, api_fhir_r4/tests/test_api_claim.py, api_fhir_r4/tests/test_api_communication.py, api_fhir_r4/tests/test_api_communicationRequest.py, api_fhir_r4/tests/test_api_contract.py, api_fhir_r4/tests/test_api_group.py, api_fhir_r4/tests/test_api_invoice.py, api_fhir_r4/tests/test_api_login.py, api_fhir_r4/tests/test_api_patient.py, api_fhir_r4/tests/test_invoiceConverter.py
[https://openimis.atlassian.net/browse/OE0-95](https://openimis.atlassian.net/browse/OE0-95)
Changes:
- Replaced mocking of `Invoice.line_items` with saving a model for the test and removing it after
- Moved log in helper methods from `test_api_login` to separate mixin to reuse in other api tests
- Fixed wrong import in `FhirConverterTestMixin`
- Cleaned repeating "create user" code from api tests
=> OE0-95: Fix the mocking context leaking into other tests

api_fhir_r4/containedResources/containedResourceHandler.py, api_fhir_r4/containedResources/converterUtils.py, api_fhir_r4/containedResources/converters.py, api_fhir_r4/converters/healthFacilityOrganisationConverter.py, api_fhir_r4/converters/medicationConverter.py, api_fhir_r4/converters/patientConverter.py, api_fhir_r4/mapping/claimMapping.py, api_fhir_r4/serializers/activityDefinitionSerializer.py, api_fhir_r4/serializers/claimSerializer.py, api_fhir_r4/serializers/groupSerializer.py, api_fhir_r4/tests/test_api_patient.py
Changes made to make communication with with claim AI Server: 
* photos are no longer obligatory 
* patient doesn't have to have address
* medication package is optional
* medication care type is optional 
* added claim ai evaluation code to mappings
=> OAI-63: Improve contained resources and converters

.github/workflows/openmis-module-test.yml, api_fhir_r4/tests/test_api_authorization.py
TICKET: [OP-475](https://openimis.atlassian.net/browse/OP-475)
=> OP-475: Disable REMOTE USER AUTH in CI tests, fixed tests

api_fhir_r4/configurations/R4SubscriptionConfig.py, api_fhir_r4/configurations/__init__.py, api_fhir_r4/converters/subscriptionConverter.py, api_fhir_r4/defaultConfig.py, api_fhir_r4/permissions.py, api_fhir_r4/serializers/subscriptionSerializer.py, api_fhir_r4/services.py, api_fhir_r4/validation.py, api_fhir_r4/views/fhir/subscription.py
[https://openimis.atlassian.net/browse/OPL-58](https://openimis.atlassian.net/browse/OPL-58)
This PR depends on https://github.com/openimis/openimis-be-api_fhir_r4_py/pull/84
Changes:
- Added subscription permission group (CRUD) and assigned them to respective actions
- Added validation to resource requested by the subscription (Does the user have permissions to read the resources)
=> OPL-58: Add authorization to Subscription endpoints (owner/permissions)

api_fhir_r4/serializers/groupSerializer.py, api_fhir_r4/serializers/patientSerializer.py
[https://openimis.atlassian.net/browse/OPL-71](https://openimis.atlassian.net/browse/OPL-71)
This PR depends on https://github.com/openimis/openimis-be-insuree_py/pull/32
Changes:
- Adjusted serializers to use services instead of mutation code
=> OPL-71 Move Insuree business logic from GQL mutations to services

README.md, api_fhir_r4/configurations/R4SubscriptionConfig.py, api_fhir_r4/configurations/__init__.py, api_fhir_r4/converters/contractConverter.py, api_fhir_r4/defaultConfig.py, api_fhir_r4/migrations/0004_update_subscription_criteria.py, api_fhir_r4/signals.py, api_fhir_r4/subscriptions/subscriptionConverter.py, api_fhir_r4/subscriptions/subscriptionCriteriaFilter.py, api_fhir_r4/subscriptions/subscriptionSerializer.py, api_fhir_r4/tests/mixin/SubscriptionTestMixin.py, api_fhir_r4/views/fhir/subscription.py
[https://openimis.atlassian.net/browse/OPL-92](https://openimis.atlassian.net/browse/OPL-92)
Changes:
- Updated subscription `criteria` definition to split `resource` and `resource type`
- Added migration to update existing subscriptions
- Updated all endpoint components to reflect the new criteria
- Updated `SubscriptionCriteriaFilter` to include both resource and resource type in initial subscription fetch
- Added README entry for subscription notification feature
=> OPL-92: Enhance the way subscription criteria store the resource type

api_fhir_r4/converters/patientConverter.py, api_fhir_r4/serializers/patientSerializer.py, api_fhir_r4/tests/mixin/patientTestMixin.py, api_fhir_r4/tests/test_api_patient.py
Part of [OE0-106](https://openimis.atlassian.net/browse/OE0-106)
**Changes:**
- It's no longer possible to create insuree with empty chf_id.
- current_address is text field in Patient's current_village address. 
- If patient is without family, home address is used as family location. 
- If patient is part of family but isHead is true then exception is raised (previously new family not related to previous one was created). 
- If general practitioner is provided in POST payload, it's used as patient's health facility.
Note: Currently it is not possible to specify current_address without also specifying current_village.
=> OE0-106: Fixed patient address

api_fhir_r4/permissions.py, api_fhir_r4/tests/test_api_authorization.py, api_fhir_r4/views/fhir/invoice.py, api_fhir_r4/views/fhir/organisation.py, api_fhir_r4/views/fhir/practitioner.py, api_fhir_r4/views/fhir/practitioner_role.py
TICKET: https://openimis.atlassian.net/browse/OE0-107
Changes: 
- added new permission classes 
- modified views by updating permission classes in multizerialized classes
- fix bug in InsuranceOrganization when we don't have pemissions to fetch InsuranceOrganization
- minor code refactor in imports
Note: In the future we can rename some names of permission classes.
=> OE0-107: modified validity of permissions in multizerialized classes

api_fhir_r4/migrations/0004_update_subscription_criteria.py
The jsoncontainskey is used with an exact match but with an operator that is not supported on Postgresql, so switching to __has_key
=> Fix migration jsoncontainskey

.github/workflows/openmis-module-test.yml, api_fhir_r4/signals.py
[https://openimis.atlassian.net/browse/OTC-843](https://openimis.atlassian.net/browse/OTC-843)
Changes:
- Fixed bill/invoice subscription hooks when the result value is None
- Updated ubuntu to 20.04 in CI workflow
=> OTC-843 modular IMIS: wrong reaction on duplicated underwriting of a policy

api_fhir_r4/apps.py, api_fhir_r4/configurations/moduleConfiguration.py, api_fhir_r4/exceptions/fhir_api_exception_handler.py
Ticket: https://openimis.atlassian.net/browse/OP-1401
Changes:
- Changed fhir api exception handler to a generic one from be_py module
- Main module will now call exception handler from rhir_api instead of being overwritten by it
Required PR:
https://github.com/openimis/openimis-be_py/pull/137
=> OP-1401: Exception handler rework.

api_fhir_r4/multiserializer/mixins.py
The practitioners are a joined set of claim admins and enrollment officers. When listing them, the result is paginated. To do so, they are merged and iterated over.
However, with the demo data, we obtained duplicates and an IndexError in the last page.
Iterate over all the pages when listing practitioners with the demo data
The duplicates are due to a wrong slice of the sets: it slices until the last index that has been listed in the previous page rather than from.
The IndexError is due to the fact that the last index of the last step will be always out of the bounds used to return the right set, i.e. here the last one.
This does not yet include tests to reproduce the bug.
=> Fix pagination bug when listing practitioner

api_fhir_r4/converters/medicationConverter.py, api_fhir_r4/tests/mixin/medicationTestMixin.py, api_fhir_r4/tests/test/test_medication.json
When retrieving a medication, its package is represented as a text in the database. It was assumed that it would contain an amount and an unit. The first would be an integer literal, and the second a text, both would be separated by a space.
When working with the demo database, it appeared that several medications didn't have a package complying with that format: the unit is sometimes not separated from the integer by the space (e.g. `10000TABLETS`, `10ml`, `200T`), or there is only a text (e.g. `EACH`).
The API returns then an error (e.g. `invalid literal for int() with base 10: '200T'`).
* it doesn't fail and extract the correct amount
* when there isn't any literal I'm assuming there is one something (as there is one record)
Add textual package such as `100l`, `200packets`, `each`, …
=> Fix medication package conversion bug

api_fhir_r4/converters/claimAdminPractitionerConverter.py, api_fhir_r4/tests/mixin/claimAdminPractitionerTestMixin.py, api_fhir_r4/tests/test/test_claimAdminPractitioner.json, api_fhir_r4/tests/test_api_claim_contained.py
At Bluesquare we are migrating the mobile apps (in the present case the one for claims) from the C# REST API to the FHIR REST API and GrapQL served by the Django app.
When retrieving claim administrators from the C# REST API, we receive for each the code of their health facility. This is not the case with the FHIR REST API.
In order to reduce the number of HTTP requests over the network, we'd like to have it in an extension:
```json
"extension":
[
{
"url": "https://openimis.github.io/openimis_fhir_r4_ig/StructureDefinition/reference",
"valueReference":
{
"reference": "Organization/12345678",
"type": "Organization",
"identifier":
{
"type":
{
"coding":
[
{
"system": "https://openimis.github.io/openimis_fhir_r4_ig/CodeSystem/openimis-identifiers",
"code": "Code"
}
]
},
"value": "12345678"
}, …
```
=> Add hf code to practitioner

api_fhir_r4/serializers/communicationSerializer.py, api_fhir_r4/tests/test_api_communication.py
When creating a Feedback with the FHIR API, only the Feedback object is created. However, on the Claim side, there are a few fields referencing the feedback, its availability, and its status of the feedback claim (that seemed to be SELECTED (i.e. int value `4`)). The present change improves the test to check that this side is also correctly and adequately set, and the correct update of the claim is also made.
I'm not sure to what to do with FeedbackPrompt. So please tell me if there is anything to do on that side too. Thanks
=> Fix uncomplete Feedback creation (Claim side)

setup.py
This is a security update and prevents the build to work in other modules.
Please check the dependabot on develop that does the same
=> OP-1556 bump aiohttp version for security & compat
